# Generated by Django 2.1.2 on 2019-11-12 18:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam_paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Exam_paper', models.FileField(blank=True, default='Null', help_text='Upload paper ', null=True, upload_to='UPLOAD/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['', 'pdf'])])),
            ],
        ),
    ]
