# Generated by Django 2.1.2 on 2019-11-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPLOAD', '0002_answerkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerkey',
            name='Branch_sem',
            field=models.CharField(blank=True, help_text='Enter Branch_sem...', max_length=100),
        ),
        migrations.AddField(
            model_name='exam_paper',
            name='Branch_sem',
            field=models.CharField(blank=True, help_text='Enter Branch_sem...', max_length=100),
        ),
    ]
