# Generated by Django 2.1.2 on 2019-11-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPLOAD', '0003_auto_20191113_0012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answerkey',
            old_name='Branch_sem',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='exam_paper',
            name='Branch_sem',
        ),
        migrations.AddField(
            model_name='exam_paper',
            name='subject',
            field=models.CharField(blank=True, help_text='Enter subject...', max_length=100),
        ),
    ]
